import { useState } from 'react'
import { useAppData } from '../data/AppDataContext'
import { generateAIPlan } from '../services/api'
import LoadingSpinner from '../components/Common/LoadingSpinner'
import SuccessMessage from '../components/Common/SuccessMessage'
import ErrorMessage from '../components/Common/ErrorMessage'

const TASK_TYPES = [
  'Generate Project Plan',
  'Break Requirement into Tasks',
  'Recommend Next Task',
  'Identify Project Blockers',
  'Explain Implementation',
  'Generate Testing Checklist',
]

function AIMentorPage() {
  const { projects, addAIHistory, addTask } = useAppData()
  const [form, setForm] = useState({
    projectId: projects[0]?.id || '',
    requirement: '',
    taskType: 'Break Requirement into Tasks',
  })
  const [errors, setErrors] = useState({})
  const [loading, setLoading] = useState(false)
  const [response, setResponse] = useState(null)
  const [success, setSuccess] = useState('')
  const [error, setError] = useState('')

  const validate = () => {
    const next = {}
    if (!form.projectId) next.projectId = 'Please select a project.'
    if (!form.requirement.trim()) next.requirement = 'Please enter a requirement or question.'
    setErrors(next)
    return Object.keys(next).length === 0
  }

  const handleGenerate = async (e) => {
    e.preventDefault()
    if (!validate()) return
    setLoading(true)
    setError('')
    setResponse(null)
    try {
      // Calls the service layer; currently returns mock data.
      const data = await generateAIPlan({
        projectId: form.projectId,
        requirement: form.requirement,
        taskType: form.taskType,
      })
      setResponse(data)
    } catch {
      setError('AI Mentor is temporarily unavailable. Please try again.')
    } finally {
      setLoading(false)
    }
  }

  const handleSave = () => {
    const project = projects.find((p) => p.id === Number(form.projectId))
    addAIHistory({
      projectId: Number(form.projectId),
      projectName: project?.name || 'Unknown',
      taskType: form.taskType,
      userPrompt: form.requirement,
      responsePreview: response?.recommendedNextAction || 'Saved recommendation.',
      modelName: 'gpt-oss:20b',
    })
    setSuccess('Recommendation saved to AI History.')
  }

  const handleCreateTasks = () => {
    const allTasks = [
      ...(response?.frontendTasks || []).map((t) => ({ title: t, area: 'Frontend' })),
      ...(response?.backendTasks || []).map((t) => ({ title: t, area: 'Backend' })),
      ...(response?.databaseTasks || []).map((t) => ({ title: t, area: 'Database' })),
    ]
    allTasks.forEach((t) => {
      addTask({
        projectId: Number(form.projectId),
        title: `[${t.area}] ${t.title}`,
        description: `Generated by AI Mentor from: ${form.requirement}`,
        priority: 'Medium',
        status: 'Pending',
        aiGenerated: true,
      })
    })
    setSuccess(`${allTasks.length} tasks created from the recommendation.`)
  }

  const handleClear = () => {
    setResponse(null)
    setForm({ ...form, requirement: '' })
    setErrors({})
  }

  return (
    <div className="page">
      {success && <SuccessMessage message={success} onDismiss={() => setSuccess('')} />}
      {error && <ErrorMessage message={error} onDismiss={() => setError('')} />}

      <section className="card">
        <div className="card-header">
          <h2 className="card-title">Ask the AI Mentor</h2>
        </div>
        <div className="card-body">
          <form className="form" onSubmit={handleGenerate} noValidate>
            <div className="form-row">
              <div className="form-field">
                <label htmlFor="ai-project" className="form-label">Select Project</label>
                <select
                  id="ai-project"
                  className="form-input"
                  value={form.projectId}
                  onChange={(e) => setForm({ ...form, projectId: Number(e.target.value) })}
                  aria-invalid={!!errors.projectId}
                >
                  <option value="">Select a project...</option>
                  {projects.map((p) => (
                    <option key={p.id} value={p.id}>{p.name}</option>
                  ))}
                </select>
                {errors.projectId && <span className="form-error">{errors.projectId}</span>}
              </div>

              <div className="form-field">
                <label htmlFor="ai-task-type" className="form-label">AI Task Type</label>
                <select
                  id="ai-task-type"
                  className="form-input"
                  value={form.taskType}
                  onChange={(e) => setForm({ ...form, taskType: e.target.value })}
                >
                  {TASK_TYPES.map((t) => <option key={t} value={t}>{t}</option>)}
                </select>
              </div>
            </div>

            <div className="form-field">
              <label htmlFor="ai-requirement" className="form-label">Requirement or Question</label>
              <textarea
                id="ai-requirement"
                className="form-input form-textarea"
                rows={4}
                placeholder="Describe what you want the AI mentor to help with..."
                value={form.requirement}
                onChange={(e) => setForm({ ...form, requirement: e.target.value })}
                aria-invalid={!!errors.requirement}
              />
              {errors.requirement && <span className="form-error">{errors.requirement}</span>}
            </div>

            <div className="form-actions">
              <button type="submit" className="btn btn-primary" disabled={loading}>
                Generate AI Recommendation
              </button>
            </div>
          </form>
        </div>
      </section>

      {loading && (
        <LoadingSpinner message="AI Mentor is analysing your project..." />
      )}

      {response && !loading && (
        <section className="card">
          <div className="card-header">
            <h2 className="card-title">AI Recommendation</h2>
            <span className="badge badge-tech-gpt-oss">gpt-oss:20b</span>
          </div>
          <div className="card-body">
            <div className="ai-section">
              <h3 className="ai-section-title">Requirement Understanding</h3>
              <p>{response.requirementUnderstanding}</p>
            </div>

            <div className="ai-grid">
              <div className="ai-section">
                <h3 className="ai-section-title">Frontend Tasks</h3>
                <ul className="ai-list">{response.frontendTasks.map((t, i) => <li key={i}>{t}</li>)}</ul>
              </div>
              <div className="ai-section">
                <h3 className="ai-section-title">Backend Tasks</h3>
                <ul className="ai-list">{response.backendTasks.map((t, i) => <li key={i}>{t}</li>)}</ul>
              </div>
              <div className="ai-section">
                <h3 className="ai-section-title">Database Tasks</h3>
                <ul className="ai-list">{response.databaseTasks.map((t, i) => <li key={i}>{t}</li>)}</ul>
              </div>
              <div className="ai-section">
                <h3 className="ai-section-title">Testing Steps</h3>
                <ul className="ai-list">{response.testingSteps.map((t, i) => <li key={i}>{t}</li>)}</ul>
              </div>
            </div>

            <div className="ai-section">
              <h3 className="ai-section-title">Possible Blockers</h3>
              <ul className="ai-list">{response.possibleBlockers.map((t, i) => <li key={i}>{t}</li>)}</ul>
            </div>

            <div className="ai-section ai-recommend">
              <h3 className="ai-section-title">Recommended Next Action</h3>
              <p>{response.recommendedNextAction}</p>
            </div>

            <div className="form-actions">
              <button className="btn btn-primary" onClick={handleSave}>Save Recommendation</button>
              <button className="btn btn-secondary" onClick={handleCreateTasks}>
                Create Tasks from Recommendation
              </button>
              <button className="btn btn-ghost" onClick={handleClear}>Clear Response</button>
            </div>
          </div>
        </section>
      )}
    </div>
  )
}

export default AIMentorPage
